name: Node.js CI

on:
  push:
    branches: [dz4]
  pull_request:
    branches: [dz4]

env:
  API_URL: https://api.react-learning.ru/v2/sb-4
  PUBLIC_URL: https://zebrooo.github.io/psychic-waffle.github.io
  PUBLIC_PATH: /psychic-waffle.github.io

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/dz4'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
